apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: text-search
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ES_HOST: "elasticsearch"
  ES_PORT: "9200"
  MINIO_ENDPOINT: "minio:9000"
  SPARK_MASTER: "spark://spark-master:7077"